### ISSUE TITLE
nfdump1.6.20 -c (limit the number of records) not working properly

### ISSUE THREAD

**Issue by namlicniku** [phaag/nfdump#226]
Limit the number of records (nfdump -c) is not limiting filtered **output**, but number of records **entering** to nfdump

Example: I want 10 flows to port 53 but I get only 2
```
mstepanek@nagios18:~$ /usr/local/bin/nfdump -M /data/nfsen/profiles-data/live/gw-vich-x86 -T -r 2020/05/24/nfcapd.202005240000 -m -c 10 'dst port 53'
Option -m deprecated. Use '-O tstart' instead

Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2020-05-23 23:59:44.975     0.000 UDP      10.112.115.15:51575 ->       10.112.1.1:53           1       66     1
2020-05-23 23:59:44.975     0.000 UDP      10.112.115.15:64952 ->       10.112.1.1:53           1       66     1
Summary: total flows: 2, total bytes: 132, total packets: 2, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: 2020-05-23 23:54:45 - 2020-05-24 00:04:44
Total flows processed: 18720, Blocks skipped: 0, Bytes read: 1048396
Sys: 0.003s flows/second: 5655589.1  Wall: 0.002s flows/second: 8132059.1
```

It seems that there is no so much flows to port 53 but if I list first 20 flows without any filter, I see that there is a lot of flows to port 53 not only two
```
mstepanek@nagios18:~$ /usr/local/bin/nfdump -M /data/nfsen/profiles-data/live/gw-vich-x86 -T -r 2020/05/24/nfcapd.202005240000 -m -c 20
Option -m deprecated. Use '-O tstart' instead

Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2020-05-23 23:59:28.705    16.260 TCP      157.240.30.34:443   ->   10.112.200.155:47010       10     1050     1
2020-05-23 23:59:30.975    13.990 TCP      10.112.129.88:52940 ->   204.79.197.200:443         28    15622     1
2020-05-23 23:59:30.975    13.990 TCP     204.79.197.200:443   ->    10.112.129.88:52940       24     9130     1
2020-05-23 23:59:34.975    10.000 TCP      10.112.105.20:55975 ->     212.67.66.77:8083        20     1330     1
2020-05-23 23:59:34.985    10.000 TCP       212.67.66.77:8083  ->    10.112.105.20:55975       10    21693     1
2020-05-23 23:59:44.975     0.000 UDP         10.112.1.1:53    ->    10.112.83.149:56022        1      428     1
2020-05-23 23:59:44.975     0.000 UDP      10.112.105.20:39058 ->       10.112.1.1:53           1       75     1
2020-05-23 23:59:44.975     0.000 UDP            8.8.8.8:53    ->     77.48.21.190:41901        1      172     1
2020-05-23 23:59:44.975     0.000 UDP         10.112.1.1:53    ->    10.112.115.15:51575        1      341     1
2020-05-23 23:59:44.975     0.000 UDP         10.112.1.1:53    ->    10.112.115.15:64952        1      341     1
2020-05-23 23:59:44.975     0.000 TCP         13.80.7.77:443   ->    10.112.129.20:57065        8     8834     1
2020-05-23 23:59:44.975     0.000 UDP      10.112.115.15:51575 ->       10.112.1.1:53           1       66     1
2020-05-23 23:59:44.975     0.000 UDP         10.112.1.1:53    ->    10.112.105.20:39058        1      375     1
2020-05-23 23:59:44.975     0.000 UDP      10.112.115.15:64952 ->       10.112.1.1:53           1       66     1
2020-05-23 23:59:44.975     0.000 TCP       10.112.44.25:49401 ->     17.57.146.52:5223         2      173     1
2020-05-23 23:59:44.985     0.000 TCP       77.88.21.179:443   ->     10.112.50.14:58979        1       52     1
2020-05-23 23:59:44.985     0.000 UDP    106.217.209.112:43113 ->     10.112.55.23:57738        1      132     1
2020-05-23 23:59:44.985     0.000 UDP       10.112.1.251:53399 ->    93.89.109.206:8125         1      453     1
2020-05-23 23:59:44.985     0.000 UDP         10.112.1.1:53    ->    10.112.83.149:59527        1      395     1
2020-05-23 23:59:44.985     0.000 UDP      10.112.83.149:59527 ->       10.112.1.1:53           1       75     1
Summary: total flows: 20, total bytes: 60803, total packets: 115, avg bps: 29878, avg pps: 7, avg bpp: 528
Time window: 2020-05-23 23:54:45 - 2020-05-24 00:04:44
Total flows processed: 18720, Blocks skipped: 0, Bytes read: 1048396
Sys: 0.003s flows/second: 5518867.9  Wall: 0.002s flows/second: 7697368.4
```

here is **correct** answer from nfdump 1.6.13
```
mstepanek@nagios:~$ /usr/local/bin/nfdump -M /data/nfsen/profiles-data/live/gw-vich-x86 -T -r 2020-05-24/nfcapd.202005240000 -m -c 10 'dst port 53'
Option -m depricated. Use '-O tstart' instead

Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
2020-05-23 23:59:44.975     0.000 UDP      10.112.105.20:39058 ->       10.112.1.1:53           1       75     1
2020-05-23 23:59:44.985     0.000 UDP       10.112.89.71:56874 ->       10.112.1.1:53           1       64     1
2020-05-23 23:59:44.985     0.000 UDP      10.112.83.149:59527 ->       10.112.1.1:53           1       75     1
2020-05-23 23:59:44.995     0.000 UDP      10.112.226.51:58926 ->       10.112.1.1:53           1       69     1
2020-05-23 23:59:44.995     0.000 UDP      10.112.226.51:55448 ->       10.112.1.1:53           1       72     1
2020-05-23 23:59:45.005     0.000 UDP      10.112.226.51:64876 ->       10.112.1.1:53           1       72     1
2020-05-23 23:59:45.005     0.000 UDP      10.112.226.51:65479 ->       10.112.1.1:53           1       63     1
2020-05-23 23:59:45.005     0.000 UDP      10.112.226.51:63525 ->       10.112.1.1:53           1       72     1
2020-05-23 23:59:45.005     0.000 UDP      10.112.226.51:52182 ->       10.112.1.1:53           1       72     1
2020-05-23 23:59:45.015     0.000 UDP       10.112.84.14:43682 ->       10.112.1.1:53           1       64     1
Summary: total flows: 10, total bytes: 698, total packets: 10, avg bps: 139599, avg pps: 249, avg bpp: 69
Time window: 2020-05-23 23:54:45 - 2020-05-24 00:04:44
Total flows processed: 18720, Blocks skipped: 0, Bytes read: 1048396
Sys: 0.004s flows/second: 4680000.0  Wall: 0.004s flows/second: 3884623.4

```

**Comment by phaag** [comment]
Thx! - Fixed in master repo.

**Comment by shartge** [comment]
Sorry, but I have to disagree, this bug does not seem closed to me. I am using git 50df654e8 and I can still reproduce this issue:

With `-c 10000` nfdump only shows the packages from the first file. This is also shown by the 5 minute time window it displays:
```
# nfdump -M /var/nfdump/profiles-data/live/r01-2:r01-1  -T  -R 2020/07/01/nfcapd.202007011155:2020/07/01/nfcapd.202007011700 '(dst ip xxx.yyy241.65 or dst ip xxx.yyy241.79) and (src xip aaa.bbb.7.12 or src xip aaa.bbb.7.29 or src xip aaa.bbb.7.39) and (asa event create)' -c 10000
Date first seen          Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte
2020-07-01 11:55:05.247     ADD  Ignore TCP         10.0.4.170:55008 ->   xxx.yyy.241.65:443       aaa.bbb.7.12:55008 ->   xxx.yyy.241.65:443          0        0
2020-07-01 11:55:11.007     ADD  Ignore TCP         10.0.4.170:55010 ->   xxx.yyy.241.65:443       aaa.bbb.7.12:55010 ->   xxx.yyy.241.65:443          0        0
2020-07-01 11:55:15.652     ADD  Ignore TCP         10.0.4.170:55012 ->   xxx.yyy.241.65:443       aaa.bbb.7.12:55012 ->   xxx.yyy.241.65:443          0        0
2020-07-01 11:55:15.710     ADD  Ignore TCP         10.0.4.170:55014 ->   xxx.yyy.241.65:443       aaa.bbb.7.12:55014 ->   xxx.yyy.241.65:443          0        0
2020-07-01 11:55:16.809     ADD  Ignore TCP         10.0.4.170:55016 ->   xxx.yyy.241.65:443       aaa.bbb.7.12:55016 ->   xxx.yyy.241.65:443          0        0
Summary: total flows: 5, total bytes: 0, total packets: 0, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: 2020-07-01 11:54:59 - 2020-07-01 11:59:59
Total flows processed: 10485, Blocks skipped: 0, Bytes read: 1048564
Sys: 0.008s flows/second: 1227751.8  Wall: 0.004s flows/second: 2504777.8 
```
If I don't specify `-c xxx` it shows me all flows:
```
# nfdump -M /var/nfdump/profiles-data/live/r01-2:r01-1  -T  -R 2020/07/01/nfcapd.202007011155:2020/07/01/nfcapd.202007011700 '(dst ip aaa.bbb.241.65 or dst ip aaa.bbb.241.79) and (src xip aaa.bbb.7.12 or src xip aaa.bbb.7.29 or src xip aaa.bbb.7.39) and (asa event create)'
Date first seen          Event  XEvent Proto      Src IP Addr:Port          Dst IP Addr:Port     X-Src IP Addr:Port        X-Dst IP Addr:Port   In Byte Out Byte
2020-07-01 11:55:05.247     ADD  Ignore TCP         10.0.4.170:55008 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:55008 ->   aaa.bbb.241.65:443          0        0
2020-07-01 11:55:11.007     ADD  Ignore TCP         10.0.4.170:55010 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:55010 ->   aaa.bbb.241.65:443          0        0
2020-07-01 11:55:15.652     ADD  Ignore TCP         10.0.4.170:55012 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:55012 ->   aaa.bbb.241.65:443          0        0
2020-07-01 11:55:15.710     ADD  Ignore TCP         10.0.4.170:55014 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:55014 ->   aaa.bbb.241.65:443          0        0
2020-07-01 11:55:16.809     ADD  Ignore TCP         10.0.4.170:55016 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:55016 ->   aaa.bbb.241.65:443          0        0
2020-07-01 11:59:02.644     ADD  Ignore TCP          10.0.1.81:57914 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:57914 ->   aaa.bbb.241.79:443          0        0
2020-07-01 11:59:02.644     ADD  Ignore TCP          10.0.1.81:57915 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:57915 ->   aaa.bbb.241.79:443          0        0
2020-07-01 11:59:09.346     ADD  Ignore TCP          10.0.1.81:57918 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:57918 ->   aaa.bbb.241.79:443          0        0
2020-07-01 11:59:11.106     ADD  Ignore TCP         10.0.4.170:56374 ->   aaa.bbb.241.79:443       aaa.bbb.7.12:56374 ->   aaa.bbb.241.79:443          0        0
[...]
2020-07-01 14:57:20.431     ADD  Ignore TCP         10.0.4.170:62052 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:62052 ->   aaa.bbb.241.65:443          0        0
2020-07-01 14:57:21.549     ADD  Ignore TCP         10.0.4.170:62054 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:62054 ->   aaa.bbb.241.65:443          0        0
2020-07-01 14:58:41.627     ADD  Ignore TCP         10.0.4.170:62090 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:62090 ->   aaa.bbb.241.65:443          0        0
2020-07-01 14:58:42.586     ADD  Ignore TCP         10.0.4.170:62092 ->   aaa.bbb.241.65:443       aaa.bbb.7.12:62092 ->   aaa.bbb.241.65:443          0        0
2020-07-01 14:59:46.776     ADD  Ignore TCP          10.0.1.81:62580 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:62580 ->   aaa.bbb.241.79:443          0        0
2020-07-01 14:59:46.778     ADD  Ignore TCP          10.0.1.81:62582 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:62582 ->   aaa.bbb.241.79:443          0        0
2020-07-01 14:59:46.781     ADD  Ignore TCP          10.0.1.81:62584 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:62584 ->   aaa.bbb.241.79:443          0        0
2020-07-01 14:59:46.784     ADD  Ignore TCP          10.0.1.81:62586 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:62586 ->   aaa.bbb.241.79:443          0        0
2020-07-01 14:59:46.786     ADD  Ignore TCP          10.0.1.81:62588 ->   aaa.bbb.241.79:443       aaa.bbb.7.39:62588 ->   aaa.bbb.241.79:443          0        0
Summary: total flows: 2096, total bytes: 0, total packets: 0, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: 2020-07-01 11:54:59 - 2020-07-01 17:05:00
Total flows processed: 3761174, Blocks skipped: 0, Bytes read: 376133476
Sys: 0.785s flows/second: 4789974.2  Wall: 0.779s flows/second: 4822518.7
```
Note how the time window now matches the selected capture range.
